//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.04.12 at 03:14:00 AM PDT 
//


package com.fusiontech.bank.transports.impl;

public class TransactionTransportResponseImpl
    extends com.fusiontech.bank.transports.impl.BaseTransportResponseImpl
    implements com.fusiontech.bank.transports.TransactionTransportResponse, com.sun.xml.bind.JAXBObject, com.fusiontech.bank.model.impl.runtime.UnmarshallableObject, com.fusiontech.bank.model.impl.runtime.XMLSerializable, com.fusiontech.bank.model.impl.runtime.ValidatableObject
{

    protected com.sun.xml.bind.util.ListImpl _Transaction;
    public final static java.lang.Class version = (com.fusiontech.bank.transports.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (com.fusiontech.bank.transports.TransactionTransportResponse.class);
    }

    protected com.sun.xml.bind.util.ListImpl _getTransaction() {
        if (_Transaction == null) {
            _Transaction = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
        }
        return _Transaction;
    }

    public java.util.List getTransaction() {
        return _getTransaction();
    }

    public com.fusiontech.bank.model.impl.runtime.UnmarshallingEventHandler createUnmarshaller(com.fusiontech.bank.model.impl.runtime.UnmarshallingContext context) {
        return new com.fusiontech.bank.transports.impl.TransactionTransportResponseImpl.Unmarshaller(context);
    }

    public void serializeBody(com.fusiontech.bank.model.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = ((_Transaction == null)? 0 :_Transaction.size());
        super.serializeBody(context);
        while (idx1 != len1) {
            context.startElement("http://www.fusiontech.com/bankservice/transports/xsd/1.0", "transaction");
            int idx_0 = idx1;
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Transaction.get(idx_0 ++)), "Transaction");
            context.endNamespaceDecls();
            int idx_1 = idx1;
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Transaction.get(idx_1 ++)), "Transaction");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _Transaction.get(idx1 ++)), "Transaction");
            context.endElement();
        }
    }

    public void serializeAttributes(com.fusiontech.bank.model.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = ((_Transaction == null)? 0 :_Transaction.size());
        super.serializeAttributes(context);
        while (idx1 != len1) {
            idx1 += 1;
        }
    }

    public void serializeURIs(com.fusiontech.bank.model.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = ((_Transaction == null)? 0 :_Transaction.size());
        super.serializeURIs(context);
        while (idx1 != len1) {
            idx1 += 1;
        }
    }

    public java.lang.Class getPrimaryInterface() {
        return (com.fusiontech.bank.transports.TransactionTransportResponse.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsr\u0000\u001dcom.sun.msv.grammar.ChoiceEx"
+"p\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000\'com.sun.msv.grammar.trex.ElementPatt"
+"ern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;"
+"xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndecl"
+"aredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003sr\u0000\u0011java.lang.Boolea"
+"n\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000p\u0000sq\u0000~\u0000\u0000ppsr\u0000\u001bcom.sun.msv.grammar.Dat"
+"aExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006exc"
+"eptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0003ppsr\u0000 c"
+"om.sun.msv.datatype.xsd.IntType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000+com.sun.msv.da"
+"tatype.xsd.IntegerDerivedType\u0099\u00f1]\u0090&6k\u00be\u0002\u0000\u0001L\u0000\nbaseFacetst\u0000)Lcom"
+"/sun/msv/datatype/xsd/XSDatatypeImpl;xr\u0000*com.sun.msv.datatyp"
+"e.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.x"
+"sd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDat"
+"atypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/lang/String;L\u0000\bt"
+"ypeNameq\u0000~\u0000\u001aL\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/WhiteS"
+"paceProcessor;xpt\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0003intsr\u0000"
+"5com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0000xpsr\u0000*com.sun.msv.datatype.xsd.MaxInclusiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001"
+"\u0002\u0000\u0000xr\u0000#com.sun.msv.datatype.xsd.RangeFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\nlimi"
+"tValuet\u0000\u0012Ljava/lang/Object;xr\u00009com.sun.msv.datatype.xsd.Data"
+"TypeWithValueConstraintFacet\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xr\u0000*com.sun.msv.datat"
+"ype.xsd.DataTypeWithFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFacetFixedZ\u0000\u0012needVa"
+"lueCheckFlagL\u0000\bbaseTypeq\u0000~\u0000\u0016L\u0000\fconcreteTypet\u0000\'Lcom/sun/msv/d"
+"atatype/xsd/ConcreteType;L\u0000\tfacetNameq\u0000~\u0000\u001axq\u0000~\u0000\u0019ppq\u0000~\u0000!\u0000\u0001sr\u0000"
+"*com.sun.msv.datatype.xsd.MinInclusiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000#"
+"ppq\u0000~\u0000!\u0000\u0000sr\u0000!com.sun.msv.datatype.xsd.LongType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000"
+"~\u0000\u0015q\u0000~\u0000\u001dt\u0000\u0004longq\u0000~\u0000!sq\u0000~\u0000\"ppq\u0000~\u0000!\u0000\u0001sq\u0000~\u0000)ppq\u0000~\u0000!\u0000\u0000sr\u0000$com.su"
+"n.msv.datatype.xsd.IntegerType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0015q\u0000~\u0000\u001dt\u0000\u0007integ"
+"erq\u0000~\u0000!sr\u0000,com.sun.msv.datatype.xsd.FractionDigitsFacet\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\u0005scalexr\u0000;com.sun.msv.datatype.xsd.DataTypeWithLexic"
+"alConstraintFacetT\u0090\u001c>\u001azb\u00ea\u0002\u0000\u0000xq\u0000~\u0000&ppq\u0000~\u0000!\u0001\u0000sr\u0000#com.sun.msv.d"
+"atatype.xsd.NumberType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0017q\u0000~\u0000\u001dt\u0000\u0007decimalq\u0000~\u0000!q"
+"\u0000~\u00007t\u0000\u000efractionDigits\u0000\u0000\u0000\u0000q\u0000~\u00001t\u0000\fminInclusivesr\u0000\u000ejava.lang.L"
+"ong;\u008b\u00e4\u0090\u00cc\u008f#\u00df\u0002\u0000\u0001J\u0000\u0005valuexr\u0000\u0010java.lang.Number\u0086\u00ac\u0095\u001d\u000b\u0094\u00e0\u008b\u0002\u0000\u0000xp\u0080\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0000q\u0000~\u00001t\u0000\fmaxInclusivesq\u0000~\u0000;\u007f\u00ff\u00ff\u00ff\u00ff\u00ff\u00ff\u00ffq\u0000~\u0000,q\u0000~\u0000:sr\u0000\u0011java.lang"
+".Integer\u0012\u00e2\u00a0\u00a4\u00f7\u0081\u00878\u0002\u0000\u0001I\u0000\u0005valuexq\u0000~\u0000<\u0080\u0000\u0000\u0000q\u0000~\u0000,q\u0000~\u0000>sq\u0000~\u0000@\u007f\u00ff\u00ff\u00ffsr\u0000"
+"0com.sun.msv.grammar.Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000"
+"xq\u0000~\u0000\u0003ppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNa"
+"meq\u0000~\u0000\u001aL\u0000\fnamespaceURIq\u0000~\u0000\u001axpq\u0000~\u0000\u001eq\u0000~\u0000\u001dsq\u0000~\u0000\u0007ppsr\u0000 com.sun.m"
+"sv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~"
+"\u0000\nxq\u0000~\u0000\u0003q\u0000~\u0000\u000epsq\u0000~\u0000\u0010ppsr\u0000\"com.sun.msv.datatype.xsd.QnameType"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0017q\u0000~\u0000\u001dt\u0000\u0005QNameq\u0000~\u0000!q\u0000~\u0000Dsq\u0000~\u0000Eq\u0000~\u0000Mq\u0000~\u0000\u001dsr\u0000#"
+"com.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000"
+"~\u0000\u001aL\u0000\fnamespaceURIq\u0000~\u0000\u001axr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000)http://www.w3.org/2001/XMLSchema-instance"
+"sr\u00000com.sun.msv.grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001"
+"\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u0000\r\u0001q\u0000~\u0000Usq\u0000~\u0000Ot\u0000\u0007errorIdt\u00008http://www.fusiontec"
+"h.com/bankservice/transports/xsd/1.0q\u0000~\u0000Usq\u0000~\u0000\u0007ppsq\u0000~\u0000\tq\u0000~\u0000\u000e"
+"p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0010ppsr\u0000#com.sun.msv.datatype.xsd.StringType\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxq\u0000~\u0000\u0017q\u0000~\u0000\u001dt\u0000\u0006stringsr\u00005com.sun.msv."
+"datatype.xsd.WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000 \u0001q"
+"\u0000~\u0000Dsq\u0000~\u0000Eq\u0000~\u0000`q\u0000~\u0000\u001dsq\u0000~\u0000\u0007ppsq\u0000~\u0000Hq\u0000~\u0000\u000epq\u0000~\u0000Jq\u0000~\u0000Qq\u0000~\u0000Usq\u0000~\u0000"
+"Ot\u0000\berrorMsgq\u0000~\u0000Yq\u0000~\u0000Usr\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000"
+"~\u0000\u0002xq\u0000~\u0000\u0003ppsq\u0000~\u0000\tpp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\tpp\u0000sq\u0000~\u0000\u0007ppsq\u0000~\u0000hq\u0000~\u0000\u000epsq\u0000"
+"~\u0000Hq\u0000~\u0000\u000epsr\u00002com.sun.msv.grammar.Expression$AnyStringExpress"
+"ion\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u0000Vq\u0000~\u0000rsr\u0000 com.sun.msv.grammar.AnyNam"
+"eClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000Pq\u0000~\u0000Usq\u0000~\u0000Ot\u0000)com.fusiontech.bank.mod"
+"el.TransactionTypet\u0000+http://java.sun.com/jaxb/xjc/dummy-elem"
+"entssq\u0000~\u0000\u0007ppsq\u0000~\u0000Hq\u0000~\u0000\u000epq\u0000~\u0000Jq\u0000~\u0000Qq\u0000~\u0000Usq\u0000~\u0000Ot\u0000\u000btransactionq"
+"\u0000~\u0000Ysr\u0000\"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpT"
+"ablet\u0000/Lcom/sun/msv/grammar/ExpressionPool$ClosedHash;xpsr\u0000-"
+"com.sun.msv.grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005c"
+"ountB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$Lcom/sun/msv/grammar/Express"
+"ionPool;xp\u0000\u0000\u0000\r\u0001pq\u0000~\u0000\bq\u0000~\u0000lq\u0000~\u0000Gq\u0000~\u0000dq\u0000~\u0000xq\u0000~\u0000\u0005q\u0000~\u0000Zq\u0000~\u0000\u000fq\u0000~\u0000"
+"\u0006q\u0000~\u0000\\q\u0000~\u0000jq\u0000~\u0000nq\u0000~\u0000ox"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends com.fusiontech.bank.model.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(com.fusiontech.bank.model.impl.runtime.UnmarshallingContext context) {
            super(context, "-----");
        }

        protected Unmarshaller(com.fusiontech.bank.model.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return com.fusiontech.bank.transports.impl.TransactionTransportResponseImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        if (("transaction" == ___local)&&("http://www.fusiontech.com/bankservice/transports/xsd/1.0" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 2;
                            return ;
                        }
                        break;
                    case  0 :
                        if (("errorId" == ___local)&&("http://www.fusiontech.com/bankservice/transports/xsd/1.0" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fusiontech.bank.transports.impl.BaseTransportResponseImpl)com.fusiontech.bank.transports.impl.TransactionTransportResponseImpl.this).new Unmarshaller(context)), 1, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("errorMsg" == ___local)&&("http://www.fusiontech.com/bankservice/transports/xsd/1.0" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fusiontech.bank.transports.impl.BaseTransportResponseImpl)com.fusiontech.bank.transports.impl.TransactionTransportResponseImpl.this).new Unmarshaller(context)), 1, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        spawnHandlerFromEnterElement((((com.fusiontech.bank.transports.impl.BaseTransportResponseImpl)com.fusiontech.bank.transports.impl.TransactionTransportResponseImpl.this).new Unmarshaller(context)), 1, ___uri, ___local, ___qname, __atts);
                        return ;
                    case  2 :
                        if (("transactionId" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getTransaction().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 3, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("accountId" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getTransaction().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 3, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("customerId" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getTransaction().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 3, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("dateCreated" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getTransaction().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 3, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("type" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getTransaction().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 3, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("amount" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getTransaction().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 3, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("availableBalance" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getTransaction().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 3, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("currentBalance" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getTransaction().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 3, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("clearFlag" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getTransaction().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 3, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        _getTransaction().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 3, ___uri, ___local, ___qname, __atts)));
                        return ;
                    case  4 :
                        if (("transaction" == ___local)&&("http://www.fusiontech.com/bankservice/transports/xsd/1.0" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 2;
                            return ;
                        }
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        if (("transaction" == ___local)&&("http://www.fusiontech.com/bankservice/transports/xsd/1.0" == ___uri)) {
                            context.popAttributes();
                            state = 4;
                            return ;
                        }
                        break;
                    case  0 :
                        spawnHandlerFromLeaveElement((((com.fusiontech.bank.transports.impl.BaseTransportResponseImpl)com.fusiontech.bank.transports.impl.TransactionTransportResponseImpl.this).new Unmarshaller(context)), 1, ___uri, ___local, ___qname);
                        return ;
                    case  2 :
                        _getTransaction().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromLeaveElement((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 3, ___uri, ___local, ___qname)));
                        return ;
                    case  4 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  0 :
                        spawnHandlerFromEnterAttribute((((com.fusiontech.bank.transports.impl.BaseTransportResponseImpl)com.fusiontech.bank.transports.impl.TransactionTransportResponseImpl.this).new Unmarshaller(context)), 1, ___uri, ___local, ___qname);
                        return ;
                    case  2 :
                        _getTransaction().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromEnterAttribute((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 3, ___uri, ___local, ___qname)));
                        return ;
                    case  4 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  0 :
                        spawnHandlerFromLeaveAttribute((((com.fusiontech.bank.transports.impl.BaseTransportResponseImpl)com.fusiontech.bank.transports.impl.TransactionTransportResponseImpl.this).new Unmarshaller(context)), 1, ___uri, ___local, ___qname);
                        return ;
                    case  2 :
                        _getTransaction().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromLeaveAttribute((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 3, ___uri, ___local, ___qname)));
                        return ;
                    case  4 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  0 :
                            spawnHandlerFromText((((com.fusiontech.bank.transports.impl.BaseTransportResponseImpl)com.fusiontech.bank.transports.impl.TransactionTransportResponseImpl.this).new Unmarshaller(context)), 1, value);
                            return ;
                        case  2 :
                            _getTransaction().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromText((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 3, value)));
                            return ;
                        case  4 :
                            revertToParentFromText(value);
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
