//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.04.12 at 03:14:00 AM PDT 
//


package com.fusiontech.bank.transports;


/**
 * Java content class for getAccountList element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Documents and Settings/mberkovich/My Documents/My School/CSUN/3. 2006_Spring/COMP 380/workspace/banksystem/docroot/bankservicetransports.xsd line 23)
 * <p>
 * <pre>
 * &lt;element name="getAccountList" type="{http://www.fusiontech.com/bankservice/transports/xsd/1.0}GetAccountListTransportRequest"/>
 * </pre>
 * 
 */
public interface GetAccountList
    extends javax.xml.bind.Element, com.fusiontech.bank.transports.GetAccountListTransportRequest
{


}
