//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.04.12 at 03:14:00 AM PDT 
//


package com.fusiontech.bank.transports;


/**
 * Java content class for WithdrawTransportResponse complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Documents and Settings/mberkovich/My Documents/My School/CSUN/3. 2006_Spring/COMP 380/workspace/banksystem/docroot/bankservicetransports.xsd line 163)
 * <p>
 * <pre>
 * &lt;complexType name="WithdrawTransportResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fusiontech.com/bankservice/transports/xsd/1.0}TransactionTransportResponse">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface WithdrawTransportResponse
    extends com.fusiontech.bank.transports.TransactionTransportResponse
{


}
