//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.04.12 at 03:14:00 AM PDT 
//


package com.fusiontech.bank.model;


/**
 * Java content class for account element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Documents and Settings/mberkovich/My Documents/My School/CSUN/3. 2006_Spring/COMP 380/workspace/banksystem/docroot/bankservicemodels.xsd line 13)
 * <p>
 * <pre>
 * &lt;element name="account" type="{http://www.fusiontech.com/bankservice/model/xsd/1.0}AccountType"/>
 * </pre>
 * 
 */
public interface Account
    extends javax.xml.bind.Element, com.fusiontech.bank.model.AccountType
{


}
