//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.04.12 at 03:14:00 AM PDT 
//


package com.fusiontech.bank.model;

import javax.xml.bind.JAXBException;
import javax.xml.bind.PropertyException;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.fusiontech.bank.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class ObjectFactory
    extends com.fusiontech.bank.model.impl.runtime.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap(16, 0.75F);
    private static java.util.HashMap rootTagMap = new java.util.HashMap();
    public final static com.fusiontech.bank.model.impl.runtime.GrammarInfo grammarInfo = new com.fusiontech.bank.model.impl.runtime.GrammarInfoImpl(rootTagMap, defaultImplementations, (com.fusiontech.bank.model.ObjectFactory.class));
    public final static java.lang.Class version = (com.fusiontech.bank.model.impl.JAXBVersion.class);

    static {
        defaultImplementations.put((com.fusiontech.bank.model.Transaction.class), "com.fusiontech.bank.model.impl.TransactionImpl");
        defaultImplementations.put((com.fusiontech.bank.model.Account.class), "com.fusiontech.bank.model.impl.AccountImpl");
        defaultImplementations.put((com.fusiontech.bank.model.CardType.class), "com.fusiontech.bank.model.impl.CardTypeImpl");
        defaultImplementations.put((com.fusiontech.bank.model.CustomerType.class), "com.fusiontech.bank.model.impl.CustomerTypeImpl");
        defaultImplementations.put((com.fusiontech.bank.model.Card.class), "com.fusiontech.bank.model.impl.CardImpl");
        defaultImplementations.put((com.fusiontech.bank.model.TransactionType.class), "com.fusiontech.bank.model.impl.TransactionTypeImpl");
        defaultImplementations.put((com.fusiontech.bank.model.Customer.class), "com.fusiontech.bank.model.impl.CustomerImpl");
        defaultImplementations.put((com.fusiontech.bank.model.AccountType.class), "com.fusiontech.bank.model.impl.AccountTypeImpl");
        rootTagMap.put(new javax.xml.namespace.QName("http://www.fusiontech.com/bankservice/model/xsd/1.0", "account"), (com.fusiontech.bank.model.Account.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://www.fusiontech.com/bankservice/model/xsd/1.0", "customer"), (com.fusiontech.bank.model.Customer.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://www.fusiontech.com/bankservice/model/xsd/1.0", "card"), (com.fusiontech.bank.model.Card.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://www.fusiontech.com/bankservice/model/xsd/1.0", "transaction"), (com.fusiontech.bank.model.Transaction.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.fusiontech.bank.model
     * 
     */
    public ObjectFactory() {
        super(grammarInfo);
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface
     *     the Class object of the javacontent interface to instantiate
     * @return
     *     a new instance
     * @throws JAXBException
     *     if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @return
     *     the value of the requested property
     * @throws PropertyException
     *     when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param value
     *     the value of the property to be set
     * @param name
     *     the name of the property to retrieve
     * @throws PropertyException
     *     when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of Transaction
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fusiontech.bank.model.Transaction createTransaction()
        throws javax.xml.bind.JAXBException
    {
        return new com.fusiontech.bank.model.impl.TransactionImpl();
    }

    /**
     * Create an instance of Account
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fusiontech.bank.model.Account createAccount()
        throws javax.xml.bind.JAXBException
    {
        return new com.fusiontech.bank.model.impl.AccountImpl();
    }

    /**
     * Create an instance of CardType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fusiontech.bank.model.CardType createCardType()
        throws javax.xml.bind.JAXBException
    {
        return new com.fusiontech.bank.model.impl.CardTypeImpl();
    }

    /**
     * Create an instance of CustomerType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fusiontech.bank.model.CustomerType createCustomerType()
        throws javax.xml.bind.JAXBException
    {
        return new com.fusiontech.bank.model.impl.CustomerTypeImpl();
    }

    /**
     * Create an instance of Card
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fusiontech.bank.model.Card createCard()
        throws javax.xml.bind.JAXBException
    {
        return new com.fusiontech.bank.model.impl.CardImpl();
    }

    /**
     * Create an instance of TransactionType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fusiontech.bank.model.TransactionType createTransactionType()
        throws javax.xml.bind.JAXBException
    {
        return new com.fusiontech.bank.model.impl.TransactionTypeImpl();
    }

    /**
     * Create an instance of Customer
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fusiontech.bank.model.Customer createCustomer()
        throws javax.xml.bind.JAXBException
    {
        return new com.fusiontech.bank.model.impl.CustomerImpl();
    }

    /**
     * Create an instance of AccountType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fusiontech.bank.model.AccountType createAccountType()
        throws javax.xml.bind.JAXBException
    {
        return new com.fusiontech.bank.model.impl.AccountTypeImpl();
    }

}
