//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.04.12 at 03:14:00 AM PDT 
//


package com.fusiontech.bank.model.impl;

public class AccountTypeImpl implements com.fusiontech.bank.model.AccountType, com.sun.xml.bind.JAXBObject, com.fusiontech.bank.model.impl.runtime.UnmarshallableObject, com.fusiontech.bank.model.impl.runtime.XMLSerializable, com.fusiontech.bank.model.impl.runtime.ValidatableObject
{

    protected java.lang.String _Type;
    protected com.sun.xml.bind.util.ListImpl _Transactions;
    protected boolean has_CurrentBalance;
    protected double _CurrentBalance;
    protected boolean has_AccountId;
    protected int _AccountId;
    protected boolean has_AvailableBalance;
    protected double _AvailableBalance;
    public final static java.lang.Class version = (com.fusiontech.bank.model.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (com.fusiontech.bank.model.AccountType.class);
    }

    public java.lang.String getType() {
        return _Type;
    }

    public void setType(java.lang.String value) {
        _Type = value;
    }

    protected com.sun.xml.bind.util.ListImpl _getTransactions() {
        if (_Transactions == null) {
            _Transactions = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
        }
        return _Transactions;
    }

    public java.util.List getTransactions() {
        return _getTransactions();
    }

    public double getCurrentBalance() {
        return _CurrentBalance;
    }

    public void setCurrentBalance(double value) {
        _CurrentBalance = value;
        has_CurrentBalance = true;
    }

    public int getAccountId() {
        return _AccountId;
    }

    public void setAccountId(int value) {
        _AccountId = value;
        has_AccountId = true;
    }

    public double getAvailableBalance() {
        return _AvailableBalance;
    }

    public void setAvailableBalance(double value) {
        _AvailableBalance = value;
        has_AvailableBalance = true;
    }

    public com.fusiontech.bank.model.impl.runtime.UnmarshallingEventHandler createUnmarshaller(com.fusiontech.bank.model.impl.runtime.UnmarshallingContext context) {
        return new com.fusiontech.bank.model.impl.AccountTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(com.fusiontech.bank.model.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx2 = 0;
        final int len2 = ((_Transactions == null)? 0 :_Transactions.size());
        if (has_AccountId) {
            context.startElement("http://www.fusiontech.com/bankservice/model/xsd/1.0", "accountId");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(javax.xml.bind.DatatypeConverter.printInt(((int) _AccountId)), "AccountId");
            } catch (java.lang.Exception e) {
                com.fusiontech.bank.model.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_Type!= null) {
            context.startElement("http://www.fusiontech.com/bankservice/model/xsd/1.0", "type");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _Type), "Type");
            } catch (java.lang.Exception e) {
                com.fusiontech.bank.model.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (has_CurrentBalance) {
            context.startElement("http://www.fusiontech.com/bankservice/model/xsd/1.0", "currentBalance");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(javax.xml.bind.DatatypeConverter.printDouble(((double) _CurrentBalance)), "CurrentBalance");
            } catch (java.lang.Exception e) {
                com.fusiontech.bank.model.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (has_AvailableBalance) {
            context.startElement("http://www.fusiontech.com/bankservice/model/xsd/1.0", "availableBalance");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(javax.xml.bind.DatatypeConverter.printDouble(((double) _AvailableBalance)), "AvailableBalance");
            } catch (java.lang.Exception e) {
                com.fusiontech.bank.model.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        while (idx2 != len2) {
            context.startElement("http://www.fusiontech.com/bankservice/model/xsd/1.0", "transactions");
            int idx_8 = idx2;
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Transactions.get(idx_8 ++)), "Transactions");
            context.endNamespaceDecls();
            int idx_9 = idx2;
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Transactions.get(idx_9 ++)), "Transactions");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _Transactions.get(idx2 ++)), "Transactions");
            context.endElement();
        }
    }

    public void serializeAttributes(com.fusiontech.bank.model.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx2 = 0;
        final int len2 = ((_Transactions == null)? 0 :_Transactions.size());
        while (idx2 != len2) {
            idx2 += 1;
        }
    }

    public void serializeURIs(com.fusiontech.bank.model.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx2 = 0;
        final int len2 = ((_Transactions == null)? 0 :_Transactions.size());
        while (idx2 != len2) {
            idx2 += 1;
        }
    }

    public java.lang.Class getPrimaryInterface() {
        return (com.fusiontech.bank.model.AccountType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsr\u0000\u001dcom.sun.msv."
+"grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000\'com.sun.msv.grammar."
+"trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/gr"
+"ammar/NameClass;xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
+"\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003sr\u0000\u0011"
+"java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000p\u0000sq\u0000~\u0000\u0000ppsr\u0000\u001bcom.sun"
+".msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype"
+"/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPa"
+"ir;xq\u0000~\u0000\u0003ppsr\u0000 com.sun.msv.datatype.xsd.IntType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr"
+"\u0000+com.sun.msv.datatype.xsd.IntegerDerivedType\u0099\u00f1]\u0090&6k\u00be\u0002\u0000\u0001L\u0000\nb"
+"aseFacetst\u0000)Lcom/sun/msv/datatype/xsd/XSDatatypeImpl;xr\u0000*com"
+".sun.msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.su"
+"n.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.da"
+"tatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/"
+"lang/String;L\u0000\btypeNameq\u0000~\u0000\u001cL\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/dat"
+"atype/xsd/WhiteSpaceProcessor;xpt\u0000 http://www.w3.org/2001/XM"
+"LSchemat\u0000\u0003intsr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcesso"
+"r$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpace"
+"Processor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u0000*com.sun.msv.datatype.xsd.MaxInclus"
+"iveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000#com.sun.msv.datatype.xsd.RangeFacet\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\nlimitValuet\u0000\u0012Ljava/lang/Object;xr\u00009com.sun.msv.d"
+"atatype.xsd.DataTypeWithValueConstraintFacet\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xr\u0000*c"
+"om.sun.msv.datatype.xsd.DataTypeWithFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFac"
+"etFixedZ\u0000\u0012needValueCheckFlagL\u0000\bbaseTypeq\u0000~\u0000\u0018L\u0000\fconcreteTypet"
+"\u0000\'Lcom/sun/msv/datatype/xsd/ConcreteType;L\u0000\tfacetNameq\u0000~\u0000\u001cxq"
+"\u0000~\u0000\u001bppq\u0000~\u0000#\u0000\u0001sr\u0000*com.sun.msv.datatype.xsd.MinInclusiveFacet\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000%ppq\u0000~\u0000#\u0000\u0000sr\u0000!com.sun.msv.datatype.xsd.LongTy"
+"pe\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0017q\u0000~\u0000\u001ft\u0000\u0004longq\u0000~\u0000#sq\u0000~\u0000$ppq\u0000~\u0000#\u0000\u0001sq\u0000~\u0000+ppq"
+"\u0000~\u0000#\u0000\u0000sr\u0000$com.sun.msv.datatype.xsd.IntegerType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000"
+"~\u0000\u0017q\u0000~\u0000\u001ft\u0000\u0007integerq\u0000~\u0000#sr\u0000,com.sun.msv.datatype.xsd.Fraction"
+"DigitsFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\u0005scalexr\u0000;com.sun.msv.datatype.xsd.D"
+"ataTypeWithLexicalConstraintFacetT\u0090\u001c>\u001azb\u00ea\u0002\u0000\u0000xq\u0000~\u0000(ppq\u0000~\u0000#\u0001\u0000s"
+"r\u0000#com.sun.msv.datatype.xsd.NumberType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0019q\u0000~\u0000\u001f"
+"t\u0000\u0007decimalq\u0000~\u0000#q\u0000~\u00009t\u0000\u000efractionDigits\u0000\u0000\u0000\u0000q\u0000~\u00003t\u0000\fminInclusiv"
+"esr\u0000\u000ejava.lang.Long;\u008b\u00e4\u0090\u00cc\u008f#\u00df\u0002\u0000\u0001J\u0000\u0005valuexr\u0000\u0010java.lang.Number\u0086\u00ac"
+"\u0095\u001d\u000b\u0094\u00e0\u008b\u0002\u0000\u0000xp\u0080\u0000\u0000\u0000\u0000\u0000\u0000\u0000q\u0000~\u00003t\u0000\fmaxInclusivesq\u0000~\u0000=\u007f\u00ff\u00ff\u00ff\u00ff\u00ff\u00ff\u00ffq\u0000~\u0000.q\u0000"
+"~\u0000<sr\u0000\u0011java.lang.Integer\u0012\u00e2\u00a0\u00a4\u00f7\u0081\u00878\u0002\u0000\u0001I\u0000\u0005valuexq\u0000~\u0000>\u0080\u0000\u0000\u0000q\u0000~\u0000.q\u0000"
+"~\u0000@sq\u0000~\u0000B\u007f\u00ff\u00ff\u00ffsr\u00000com.sun.msv.grammar.Expression$NullSetExpre"
+"ssion\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB"
+"\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u001cL\u0000\fnamespaceURIq\u0000~\u0000\u001cxpq\u0000~\u0000 q\u0000~\u0000\u001fsq\u0000~\u0000"
+"\tppsr\u0000 com.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000"
+"\u0002L\u0000\tnameClassq\u0000~\u0000\fxq\u0000~\u0000\u0003q\u0000~\u0000\u0010psq\u0000~\u0000\u0012ppsr\u0000\"com.sun.msv.dataty"
+"pe.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0019q\u0000~\u0000\u001ft\u0000\u0005QNameq\u0000~\u0000#q\u0000~\u0000Fsq\u0000~"
+"\u0000Gq\u0000~\u0000Oq\u0000~\u0000\u001fsr\u0000#com.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
+"\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u001cL\u0000\fnamespaceURIq\u0000~\u0000\u001cxr\u0000\u001dcom.sun.msv.gramm"
+"ar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000)http://www.w3.org/2001/XM"
+"LSchema-instancesr\u00000com.sun.msv.grammar.Expression$EpsilonEx"
+"pression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u0000\u000f\u0001q\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\taccountIdt\u00003ht"
+"tp://www.fusiontech.com/bankservice/model/xsd/1.0q\u0000~\u0000Wsq\u0000~\u0000\t"
+"ppsq\u0000~\u0000\u000bq\u0000~\u0000\u0010p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0012ppsr\u0000#com.sun.msv.datatype.xsd."
+"StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxq\u0000~\u0000\u0019q\u0000~\u0000\u001ft\u0000\u0006stringsr\u0000"
+"5com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\"\u0001q\u0000~\u0000Fsq\u0000~\u0000Gq\u0000~\u0000bq\u0000~\u0000\u001fsq\u0000~\u0000\tppsq\u0000~\u0000Jq\u0000~\u0000\u0010pq\u0000~\u0000Lq\u0000"
+"~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\u0004typeq\u0000~\u0000[q\u0000~\u0000Wsq\u0000~\u0000\tppsq\u0000~\u0000\u000bq\u0000~\u0000\u0010p\u0000sq\u0000~\u0000\u0000pp"
+"sq\u0000~\u0000\u0012ppsr\u0000#com.sun.msv.datatype.xsd.DoubleType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr"
+"\u0000+com.sun.msv.datatype.xsd.FloatingNumberType\u00fc\u00e3\u00b6\u0087\u008c\u00a8|\u00e0\u0002\u0000\u0000xq\u0000~"
+"\u0000\u0019q\u0000~\u0000\u001ft\u0000\u0006doubleq\u0000~\u0000#q\u0000~\u0000Fsq\u0000~\u0000Gq\u0000~\u0000qq\u0000~\u0000\u001fsq\u0000~\u0000\tppsq\u0000~\u0000Jq\u0000~\u0000"
+"\u0010pq\u0000~\u0000Lq\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\u000ecurrentBalanceq\u0000~\u0000[q\u0000~\u0000Wsq\u0000~\u0000\tppsq"
+"\u0000~\u0000\u000bq\u0000~\u0000\u0010p\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000msq\u0000~\u0000\tppsq\u0000~\u0000Jq\u0000~\u0000\u0010pq\u0000~\u0000Lq\u0000~\u0000Sq\u0000~\u0000Ws"
+"q\u0000~\u0000Qt\u0000\u0010availableBalanceq\u0000~\u0000[q\u0000~\u0000Wsq\u0000~\u0000\tppsr\u0000 com.sun.msv.gr"
+"ammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryEx"
+"p\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002xq\u0000~\u0000\u0003q\u0000~\u0000\u0010psq\u0000~\u0000\u000bq\u0000~\u0000\u0010p\u0000sq\u0000~\u0000\u0000ppsq\u0000~"
+"\u0000\u000bpp\u0000sq\u0000~\u0000\tppsq\u0000~\u0000\u007fq\u0000~\u0000\u0010psq\u0000~\u0000Jq\u0000~\u0000\u0010psr\u00002com.sun.msv.grammar"
+".Expression$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u0000Xq\u0000~\u0000\u0089sr"
+"\u0000 com.sun.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000Rq\u0000~\u0000Wsq\u0000~"
+"\u0000Qt\u0000)com.fusiontech.bank.model.TransactionTypet\u0000+http://java"
+".sun.com/jaxb/xjc/dummy-elementssq\u0000~\u0000\tppsq\u0000~\u0000Jq\u0000~\u0000\u0010pq\u0000~\u0000Lq\u0000~"
+"\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\ftransactionsq\u0000~\u0000[q\u0000~\u0000Wsr\u0000\"com.sun.msv.gramma"
+"r.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/gramma"
+"r/ExpressionPool$ClosedHash;xpsr\u0000-com.sun.msv.grammar.Expres"
+"sionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006par"
+"entt\u0000$Lcom/sun/msv/grammar/ExpressionPool;xp\u0000\u0000\u0000\u0016\u0001pq\u0000~\u0000lq\u0000~\u0000y"
+"q\u0000~\u0000\nq\u0000~\u0000jq\u0000~\u0000wq\u0000~\u0000\u0083q\u0000~\u0000~q\u0000~\u0000Iq\u0000~\u0000fq\u0000~\u0000sq\u0000~\u0000zq\u0000~\u0000\u008fq\u0000~\u0000\\q\u0000~\u0000\u0007"
+"q\u0000~\u0000\u0005q\u0000~\u0000\u0011q\u0000~\u0000\bq\u0000~\u0000^q\u0000~\u0000\u0081q\u0000~\u0000\u0006q\u0000~\u0000\u0085q\u0000~\u0000\u0086x"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends com.fusiontech.bank.model.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(com.fusiontech.bank.model.impl.runtime.UnmarshallingContext context) {
            super(context, "----------------");
        }

        protected Unmarshaller(com.fusiontech.bank.model.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return com.fusiontech.bank.model.impl.AccountTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  12 :
                        if (("transactions" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 13;
                            return ;
                        }
                        state = 15;
                        continue outer;
                    case  6 :
                        if (("currentBalance" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 7;
                            return ;
                        }
                        state = 9;
                        continue outer;
                    case  15 :
                        if (("transactions" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 13;
                            return ;
                        }
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  3 :
                        if (("type" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 4;
                            return ;
                        }
                        state = 6;
                        continue outer;
                    case  13 :
                        if (("transactionId" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getTransactions().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 14, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("accountId" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getTransactions().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 14, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("customerId" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getTransactions().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 14, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("dateCreated" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getTransactions().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 14, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("type" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getTransactions().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 14, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("amount" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getTransactions().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 14, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("availableBalance" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getTransactions().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 14, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("currentBalance" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getTransactions().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 14, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("clearFlag" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getTransactions().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 14, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        _getTransactions().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 14, ___uri, ___local, ___qname, __atts)));
                        return ;
                    case  0 :
                        if (("accountId" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 1;
                            return ;
                        }
                        state = 3;
                        continue outer;
                    case  9 :
                        if (("availableBalance" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 10;
                            return ;
                        }
                        state = 12;
                        continue outer;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  2 :
                        if (("accountId" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  5 :
                        if (("type" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.popAttributes();
                            state = 6;
                            return ;
                        }
                        break;
                    case  8 :
                        if (("currentBalance" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.popAttributes();
                            state = 9;
                            return ;
                        }
                        break;
                    case  11 :
                        if (("availableBalance" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.popAttributes();
                            state = 12;
                            return ;
                        }
                        break;
                    case  12 :
                        state = 15;
                        continue outer;
                    case  6 :
                        state = 9;
                        continue outer;
                    case  15 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  14 :
                        if (("transactions" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.popAttributes();
                            state = 15;
                            return ;
                        }
                        break;
                    case  3 :
                        state = 6;
                        continue outer;
                    case  13 :
                        _getTransactions().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromLeaveElement((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 14, ___uri, ___local, ___qname)));
                        return ;
                    case  0 :
                        state = 3;
                        continue outer;
                    case  9 :
                        state = 12;
                        continue outer;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  12 :
                        state = 15;
                        continue outer;
                    case  6 :
                        state = 9;
                        continue outer;
                    case  15 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  3 :
                        state = 6;
                        continue outer;
                    case  13 :
                        _getTransactions().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromEnterAttribute((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 14, ___uri, ___local, ___qname)));
                        return ;
                    case  0 :
                        state = 3;
                        continue outer;
                    case  9 :
                        state = 12;
                        continue outer;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  12 :
                        state = 15;
                        continue outer;
                    case  6 :
                        state = 9;
                        continue outer;
                    case  15 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  3 :
                        state = 6;
                        continue outer;
                    case  13 :
                        _getTransactions().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromLeaveAttribute((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 14, ___uri, ___local, ___qname)));
                        return ;
                    case  0 :
                        state = 3;
                        continue outer;
                    case  9 :
                        state = 12;
                        continue outer;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  12 :
                            state = 15;
                            continue outer;
                        case  10 :
                            state = 11;
                            eatText1(value);
                            return ;
                        case  6 :
                            state = 9;
                            continue outer;
                        case  4 :
                            state = 5;
                            eatText2(value);
                            return ;
                        case  15 :
                            revertToParentFromText(value);
                            return ;
                        case  3 :
                            state = 6;
                            continue outer;
                        case  13 :
                            _getTransactions().add(((com.fusiontech.bank.model.impl.TransactionTypeImpl) spawnChildFromText((com.fusiontech.bank.model.impl.TransactionTypeImpl.class), 14, value)));
                            return ;
                        case  7 :
                            state = 8;
                            eatText3(value);
                            return ;
                        case  0 :
                            state = 3;
                            continue outer;
                        case  9 :
                            state = 12;
                            continue outer;
                        case  1 :
                            state = 2;
                            eatText4(value);
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _AvailableBalance = javax.xml.bind.DatatypeConverter.parseDouble(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_AvailableBalance = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Type = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText3(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _CurrentBalance = javax.xml.bind.DatatypeConverter.parseDouble(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_CurrentBalance = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText4(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _AccountId = javax.xml.bind.DatatypeConverter.parseInt(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_AccountId = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

    }

}
