//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.04.12 at 03:14:00 AM PDT 
//


package com.fusiontech.bank.model.impl;

public class CustomerTypeImpl implements com.fusiontech.bank.model.CustomerType, com.sun.xml.bind.JAXBObject, com.fusiontech.bank.model.impl.runtime.UnmarshallableObject, com.fusiontech.bank.model.impl.runtime.XMLSerializable, com.fusiontech.bank.model.impl.runtime.ValidatableObject
{

    protected com.sun.xml.bind.util.ListImpl _Account;
    protected java.lang.String _FirstName;
    protected com.sun.xml.bind.util.ListImpl _Card;
    protected boolean has_CustomerId;
    protected int _CustomerId;
    protected java.lang.String _LastName;
    public final static java.lang.Class version = (com.fusiontech.bank.model.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (com.fusiontech.bank.model.CustomerType.class);
    }

    protected com.sun.xml.bind.util.ListImpl _getAccount() {
        if (_Account == null) {
            _Account = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
        }
        return _Account;
    }

    public java.util.List getAccount() {
        return _getAccount();
    }

    public java.lang.String getFirstName() {
        return _FirstName;
    }

    public void setFirstName(java.lang.String value) {
        _FirstName = value;
    }

    protected com.sun.xml.bind.util.ListImpl _getCard() {
        if (_Card == null) {
            _Card = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
        }
        return _Card;
    }

    public java.util.List getCard() {
        return _getCard();
    }

    public int getCustomerId() {
        return _CustomerId;
    }

    public void setCustomerId(int value) {
        _CustomerId = value;
        has_CustomerId = true;
    }

    public java.lang.String getLastName() {
        return _LastName;
    }

    public void setLastName(java.lang.String value) {
        _LastName = value;
    }

    public com.fusiontech.bank.model.impl.runtime.UnmarshallingEventHandler createUnmarshaller(com.fusiontech.bank.model.impl.runtime.UnmarshallingContext context) {
        return new com.fusiontech.bank.model.impl.CustomerTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(com.fusiontech.bank.model.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = ((_Account == null)? 0 :_Account.size());
        int idx3 = 0;
        final int len3 = ((_Card == null)? 0 :_Card.size());
        if (has_CustomerId) {
            context.startElement("http://www.fusiontech.com/bankservice/model/xsd/1.0", "customerId");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(javax.xml.bind.DatatypeConverter.printInt(((int) _CustomerId)), "CustomerId");
            } catch (java.lang.Exception e) {
                com.fusiontech.bank.model.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_FirstName!= null) {
            context.startElement("http://www.fusiontech.com/bankservice/model/xsd/1.0", "firstName");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _FirstName), "FirstName");
            } catch (java.lang.Exception e) {
                com.fusiontech.bank.model.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_LastName!= null) {
            context.startElement("http://www.fusiontech.com/bankservice/model/xsd/1.0", "lastName");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _LastName), "LastName");
            } catch (java.lang.Exception e) {
                com.fusiontech.bank.model.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        while (idx3 != len3) {
            context.startElement("http://www.fusiontech.com/bankservice/model/xsd/1.0", "card");
            int idx_6 = idx3;
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Card.get(idx_6 ++)), "Card");
            context.endNamespaceDecls();
            int idx_7 = idx3;
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Card.get(idx_7 ++)), "Card");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _Card.get(idx3 ++)), "Card");
            context.endElement();
        }
        while (idx1 != len1) {
            context.startElement("http://www.fusiontech.com/bankservice/model/xsd/1.0", "account");
            int idx_8 = idx1;
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Account.get(idx_8 ++)), "Account");
            context.endNamespaceDecls();
            int idx_9 = idx1;
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Account.get(idx_9 ++)), "Account");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _Account.get(idx1 ++)), "Account");
            context.endElement();
        }
    }

    public void serializeAttributes(com.fusiontech.bank.model.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = ((_Account == null)? 0 :_Account.size());
        int idx3 = 0;
        final int len3 = ((_Card == null)? 0 :_Card.size());
        while (idx3 != len3) {
            idx3 += 1;
        }
        while (idx1 != len1) {
            idx1 += 1;
        }
    }

    public void serializeURIs(com.fusiontech.bank.model.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = ((_Account == null)? 0 :_Account.size());
        int idx3 = 0;
        final int len3 = ((_Card == null)? 0 :_Card.size());
        while (idx3 != len3) {
            idx3 += 1;
        }
        while (idx1 != len1) {
            idx1 += 1;
        }
    }

    public java.lang.Class getPrimaryInterface() {
        return (com.fusiontech.bank.model.CustomerType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsr\u0000\u001dcom.sun.msv."
+"grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000\'com.sun.msv.grammar."
+"trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/gr"
+"ammar/NameClass;xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
+"\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003sr\u0000\u0011"
+"java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000p\u0000sq\u0000~\u0000\u0000ppsr\u0000\u001bcom.sun"
+".msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype"
+"/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPa"
+"ir;xq\u0000~\u0000\u0003ppsr\u0000 com.sun.msv.datatype.xsd.IntType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr"
+"\u0000+com.sun.msv.datatype.xsd.IntegerDerivedType\u0099\u00f1]\u0090&6k\u00be\u0002\u0000\u0001L\u0000\nb"
+"aseFacetst\u0000)Lcom/sun/msv/datatype/xsd/XSDatatypeImpl;xr\u0000*com"
+".sun.msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.su"
+"n.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.da"
+"tatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/"
+"lang/String;L\u0000\btypeNameq\u0000~\u0000\u001cL\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/dat"
+"atype/xsd/WhiteSpaceProcessor;xpt\u0000 http://www.w3.org/2001/XM"
+"LSchemat\u0000\u0003intsr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcesso"
+"r$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpace"
+"Processor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u0000*com.sun.msv.datatype.xsd.MaxInclus"
+"iveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000#com.sun.msv.datatype.xsd.RangeFacet\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\nlimitValuet\u0000\u0012Ljava/lang/Object;xr\u00009com.sun.msv.d"
+"atatype.xsd.DataTypeWithValueConstraintFacet\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xr\u0000*c"
+"om.sun.msv.datatype.xsd.DataTypeWithFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFac"
+"etFixedZ\u0000\u0012needValueCheckFlagL\u0000\bbaseTypeq\u0000~\u0000\u0018L\u0000\fconcreteTypet"
+"\u0000\'Lcom/sun/msv/datatype/xsd/ConcreteType;L\u0000\tfacetNameq\u0000~\u0000\u001cxq"
+"\u0000~\u0000\u001bppq\u0000~\u0000#\u0000\u0001sr\u0000*com.sun.msv.datatype.xsd.MinInclusiveFacet\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000%ppq\u0000~\u0000#\u0000\u0000sr\u0000!com.sun.msv.datatype.xsd.LongTy"
+"pe\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0017q\u0000~\u0000\u001ft\u0000\u0004longq\u0000~\u0000#sq\u0000~\u0000$ppq\u0000~\u0000#\u0000\u0001sq\u0000~\u0000+ppq"
+"\u0000~\u0000#\u0000\u0000sr\u0000$com.sun.msv.datatype.xsd.IntegerType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000"
+"~\u0000\u0017q\u0000~\u0000\u001ft\u0000\u0007integerq\u0000~\u0000#sr\u0000,com.sun.msv.datatype.xsd.Fraction"
+"DigitsFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\u0005scalexr\u0000;com.sun.msv.datatype.xsd.D"
+"ataTypeWithLexicalConstraintFacetT\u0090\u001c>\u001azb\u00ea\u0002\u0000\u0000xq\u0000~\u0000(ppq\u0000~\u0000#\u0001\u0000s"
+"r\u0000#com.sun.msv.datatype.xsd.NumberType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0019q\u0000~\u0000\u001f"
+"t\u0000\u0007decimalq\u0000~\u0000#q\u0000~\u00009t\u0000\u000efractionDigits\u0000\u0000\u0000\u0000q\u0000~\u00003t\u0000\fminInclusiv"
+"esr\u0000\u000ejava.lang.Long;\u008b\u00e4\u0090\u00cc\u008f#\u00df\u0002\u0000\u0001J\u0000\u0005valuexr\u0000\u0010java.lang.Number\u0086\u00ac"
+"\u0095\u001d\u000b\u0094\u00e0\u008b\u0002\u0000\u0000xp\u0080\u0000\u0000\u0000\u0000\u0000\u0000\u0000q\u0000~\u00003t\u0000\fmaxInclusivesq\u0000~\u0000=\u007f\u00ff\u00ff\u00ff\u00ff\u00ff\u00ff\u00ffq\u0000~\u0000.q\u0000"
+"~\u0000<sr\u0000\u0011java.lang.Integer\u0012\u00e2\u00a0\u00a4\u00f7\u0081\u00878\u0002\u0000\u0001I\u0000\u0005valuexq\u0000~\u0000>\u0080\u0000\u0000\u0000q\u0000~\u0000.q\u0000"
+"~\u0000@sq\u0000~\u0000B\u007f\u00ff\u00ff\u00ffsr\u00000com.sun.msv.grammar.Expression$NullSetExpre"
+"ssion\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB"
+"\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u001cL\u0000\fnamespaceURIq\u0000~\u0000\u001cxpq\u0000~\u0000 q\u0000~\u0000\u001fsq\u0000~\u0000"
+"\tppsr\u0000 com.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000"
+"\u0002L\u0000\tnameClassq\u0000~\u0000\fxq\u0000~\u0000\u0003q\u0000~\u0000\u0010psq\u0000~\u0000\u0012ppsr\u0000\"com.sun.msv.dataty"
+"pe.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0019q\u0000~\u0000\u001ft\u0000\u0005QNameq\u0000~\u0000#q\u0000~\u0000Fsq\u0000~"
+"\u0000Gq\u0000~\u0000Oq\u0000~\u0000\u001fsr\u0000#com.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
+"\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u001cL\u0000\fnamespaceURIq\u0000~\u0000\u001cxr\u0000\u001dcom.sun.msv.gramm"
+"ar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000)http://www.w3.org/2001/XM"
+"LSchema-instancesr\u00000com.sun.msv.grammar.Expression$EpsilonEx"
+"pression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u0000\u000f\u0001q\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\ncustomerIdt\u00003h"
+"ttp://www.fusiontech.com/bankservice/model/xsd/1.0q\u0000~\u0000Wsq\u0000~\u0000"
+"\tppsq\u0000~\u0000\u000bq\u0000~\u0000\u0010p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0012ppsr\u0000#com.sun.msv.datatype.xsd"
+".StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxq\u0000~\u0000\u0019q\u0000~\u0000\u001ft\u0000\u0006stringsr"
+"\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\"\u0001q\u0000~\u0000Fsq\u0000~\u0000Gq\u0000~\u0000bq\u0000~\u0000\u001fsq\u0000~\u0000\tppsq\u0000~\u0000Jq\u0000~\u0000\u0010pq\u0000~\u0000Lq"
+"\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\tfirstNameq\u0000~\u0000[q\u0000~\u0000Wsq\u0000~\u0000\tppsq\u0000~\u0000\u000bq\u0000~\u0000\u0010p\u0000sq"
+"\u0000~\u0000\u0000ppq\u0000~\u0000_sq\u0000~\u0000\tppsq\u0000~\u0000Jq\u0000~\u0000\u0010pq\u0000~\u0000Lq\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\blastN"
+"ameq\u0000~\u0000[q\u0000~\u0000Wsq\u0000~\u0000\tppsr\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~"
+"\u0000\u0002xq\u0000~\u0000\u0003q\u0000~\u0000\u0010psq\u0000~\u0000\u000bq\u0000~\u0000\u0010p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u000bpp\u0000sq\u0000~\u0000\tppsq\u0000~\u0000rq\u0000"
+"~\u0000\u0010psq\u0000~\u0000Jq\u0000~\u0000\u0010psr\u00002com.sun.msv.grammar.Expression$AnyString"
+"Expression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003q\u0000~\u0000Xq\u0000~\u0000|sr\u0000 com.sun.msv.grammar"
+".AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000Rq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\"com.fusiontech.b"
+"ank.model.CardTypet\u0000+http://java.sun.com/jaxb/xjc/dummy-elem"
+"entssq\u0000~\u0000\tppsq\u0000~\u0000Jq\u0000~\u0000\u0010pq\u0000~\u0000Lq\u0000~\u0000Sq\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\u0004cardq\u0000~\u0000[q\u0000~"
+"\u0000Wsq\u0000~\u0000\tppsq\u0000~\u0000rq\u0000~\u0000\u0010psq\u0000~\u0000\u000bq\u0000~\u0000\u0010p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u000bpp\u0000sq\u0000~\u0000\tpp"
+"sq\u0000~\u0000rq\u0000~\u0000\u0010psq\u0000~\u0000Jq\u0000~\u0000\u0010pq\u0000~\u0000|q\u0000~\u0000~q\u0000~\u0000Wsq\u0000~\u0000Qt\u0000%com.fusionte"
+"ch.bank.model.AccountTypeq\u0000~\u0000\u0081sq\u0000~\u0000\tppsq\u0000~\u0000Jq\u0000~\u0000\u0010pq\u0000~\u0000Lq\u0000~\u0000S"
+"q\u0000~\u0000Wsq\u0000~\u0000Qt\u0000\u0007accountq\u0000~\u0000[q\u0000~\u0000Wsr\u0000\"com.sun.msv.grammar.Expre"
+"ssionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/Expre"
+"ssionPool$ClosedHash;xpsr\u0000-com.sun.msv.grammar.ExpressionPoo"
+"l$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006parentt\u0000$L"
+"com/sun/msv/grammar/ExpressionPool;xp\u0000\u0000\u0000\u0019\u0001pq\u0000~\u0000\nq\u0000~\u0000vq\u0000~\u0000\u0089q\u0000"
+"~\u0000qq\u0000~\u0000\u0086q\u0000~\u0000Iq\u0000~\u0000fq\u0000~\u0000mq\u0000~\u0000\u0082q\u0000~\u0000\u0090q\u0000~\u0000\\q\u0000~\u0000jq\u0000~\u0000\u0005q\u0000~\u0000\u0011q\u0000~\u0000\bq\u0000"
+"~\u0000^q\u0000~\u0000lq\u0000~\u0000\u0007q\u0000~\u0000tq\u0000~\u0000\u0087q\u0000~\u0000\u0006q\u0000~\u0000xq\u0000~\u0000yq\u0000~\u0000\u008cq\u0000~\u0000\u008bx"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends com.fusiontech.bank.model.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(com.fusiontech.bank.model.impl.runtime.UnmarshallingContext context) {
            super(context, "----------------");
        }

        protected Unmarshaller(com.fusiontech.bank.model.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return com.fusiontech.bank.model.impl.CustomerTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  9 :
                        if (("card" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 10;
                            return ;
                        }
                        state = 12;
                        continue outer;
                    case  15 :
                        if (("account" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 13;
                            return ;
                        }
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  6 :
                        if (("lastName" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 7;
                            return ;
                        }
                        state = 9;
                        continue outer;
                    case  12 :
                        if (("card" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 10;
                            return ;
                        }
                        if (("account" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 13;
                            return ;
                        }
                        state = 15;
                        continue outer;
                    case  10 :
                        if (("cardNumber" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getCard().add(((com.fusiontech.bank.model.impl.CardTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.CardTypeImpl.class), 11, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("cardPin" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getCard().add(((com.fusiontech.bank.model.impl.CardTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.CardTypeImpl.class), 11, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("customerId" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getCard().add(((com.fusiontech.bank.model.impl.CardTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.CardTypeImpl.class), 11, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("expirationDate" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getCard().add(((com.fusiontech.bank.model.impl.CardTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.CardTypeImpl.class), 11, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        _getCard().add(((com.fusiontech.bank.model.impl.CardTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.CardTypeImpl.class), 11, ___uri, ___local, ___qname, __atts)));
                        return ;
                    case  0 :
                        if (("customerId" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 1;
                            return ;
                        }
                        state = 3;
                        continue outer;
                    case  3 :
                        if (("firstName" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 4;
                            return ;
                        }
                        state = 6;
                        continue outer;
                    case  13 :
                        if (("accountId" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getAccount().add(((com.fusiontech.bank.model.impl.AccountTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.AccountTypeImpl.class), 14, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("type" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getAccount().add(((com.fusiontech.bank.model.impl.AccountTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.AccountTypeImpl.class), 14, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("currentBalance" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getAccount().add(((com.fusiontech.bank.model.impl.AccountTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.AccountTypeImpl.class), 14, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("availableBalance" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getAccount().add(((com.fusiontech.bank.model.impl.AccountTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.AccountTypeImpl.class), 14, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("transactions" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            _getAccount().add(((com.fusiontech.bank.model.impl.AccountTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.AccountTypeImpl.class), 14, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        _getAccount().add(((com.fusiontech.bank.model.impl.AccountTypeImpl) spawnChildFromEnterElement((com.fusiontech.bank.model.impl.AccountTypeImpl.class), 14, ___uri, ___local, ___qname, __atts)));
                        return ;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  5 :
                        if (("firstName" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.popAttributes();
                            state = 6;
                            return ;
                        }
                        break;
                    case  9 :
                        state = 12;
                        continue outer;
                    case  15 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  6 :
                        state = 9;
                        continue outer;
                    case  12 :
                        state = 15;
                        continue outer;
                    case  2 :
                        if (("customerId" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  14 :
                        if (("account" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.popAttributes();
                            state = 15;
                            return ;
                        }
                        break;
                    case  10 :
                        _getCard().add(((com.fusiontech.bank.model.impl.CardTypeImpl) spawnChildFromLeaveElement((com.fusiontech.bank.model.impl.CardTypeImpl.class), 11, ___uri, ___local, ___qname)));
                        return ;
                    case  0 :
                        state = 3;
                        continue outer;
                    case  11 :
                        if (("card" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.popAttributes();
                            state = 12;
                            return ;
                        }
                        break;
                    case  3 :
                        state = 6;
                        continue outer;
                    case  8 :
                        if (("lastName" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.popAttributes();
                            state = 9;
                            return ;
                        }
                        break;
                    case  13 :
                        _getAccount().add(((com.fusiontech.bank.model.impl.AccountTypeImpl) spawnChildFromLeaveElement((com.fusiontech.bank.model.impl.AccountTypeImpl.class), 14, ___uri, ___local, ___qname)));
                        return ;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  9 :
                        state = 12;
                        continue outer;
                    case  15 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  6 :
                        state = 9;
                        continue outer;
                    case  12 :
                        state = 15;
                        continue outer;
                    case  10 :
                        _getCard().add(((com.fusiontech.bank.model.impl.CardTypeImpl) spawnChildFromEnterAttribute((com.fusiontech.bank.model.impl.CardTypeImpl.class), 11, ___uri, ___local, ___qname)));
                        return ;
                    case  0 :
                        state = 3;
                        continue outer;
                    case  3 :
                        state = 6;
                        continue outer;
                    case  13 :
                        _getAccount().add(((com.fusiontech.bank.model.impl.AccountTypeImpl) spawnChildFromEnterAttribute((com.fusiontech.bank.model.impl.AccountTypeImpl.class), 14, ___uri, ___local, ___qname)));
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  9 :
                        state = 12;
                        continue outer;
                    case  15 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  6 :
                        state = 9;
                        continue outer;
                    case  12 :
                        state = 15;
                        continue outer;
                    case  10 :
                        _getCard().add(((com.fusiontech.bank.model.impl.CardTypeImpl) spawnChildFromLeaveAttribute((com.fusiontech.bank.model.impl.CardTypeImpl.class), 11, ___uri, ___local, ___qname)));
                        return ;
                    case  0 :
                        state = 3;
                        continue outer;
                    case  3 :
                        state = 6;
                        continue outer;
                    case  13 :
                        _getAccount().add(((com.fusiontech.bank.model.impl.AccountTypeImpl) spawnChildFromLeaveAttribute((com.fusiontech.bank.model.impl.AccountTypeImpl.class), 14, ___uri, ___local, ___qname)));
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  1 :
                            state = 2;
                            eatText1(value);
                            return ;
                        case  9 :
                            state = 12;
                            continue outer;
                        case  7 :
                            state = 8;
                            eatText2(value);
                            return ;
                        case  15 :
                            revertToParentFromText(value);
                            return ;
                        case  6 :
                            state = 9;
                            continue outer;
                        case  12 :
                            state = 15;
                            continue outer;
                        case  10 :
                            _getCard().add(((com.fusiontech.bank.model.impl.CardTypeImpl) spawnChildFromText((com.fusiontech.bank.model.impl.CardTypeImpl.class), 11, value)));
                            return ;
                        case  0 :
                            state = 3;
                            continue outer;
                        case  4 :
                            state = 5;
                            eatText3(value);
                            return ;
                        case  3 :
                            state = 6;
                            continue outer;
                        case  13 :
                            _getAccount().add(((com.fusiontech.bank.model.impl.AccountTypeImpl) spawnChildFromText((com.fusiontech.bank.model.impl.AccountTypeImpl.class), 14, value)));
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _CustomerId = javax.xml.bind.DatatypeConverter.parseInt(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_CustomerId = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _LastName = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText3(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _FirstName = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

    }

}
