//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.04.12 at 03:14:00 AM PDT 
//


package com.fusiontech.bank.model.impl;

public class TransactionTypeImpl implements com.fusiontech.bank.model.TransactionType, com.sun.xml.bind.JAXBObject, com.fusiontech.bank.model.impl.runtime.UnmarshallableObject, com.fusiontech.bank.model.impl.runtime.XMLSerializable, com.fusiontech.bank.model.impl.runtime.ValidatableObject
{

    protected boolean has_Amount;
    protected double _Amount;
    protected java.lang.String _Type;
    protected boolean has_CurrentBalance;
    protected double _CurrentBalance;
    protected java.util.Calendar _DateCreated;
    protected boolean has_AccountId;
    protected int _AccountId;
    protected boolean has_CustomerId;
    protected int _CustomerId;
    protected boolean has_TransactionId;
    protected int _TransactionId;
    protected boolean has_ClearFlag;
    protected int _ClearFlag;
    protected boolean has_AvailableBalance;
    protected double _AvailableBalance;
    public final static java.lang.Class version = (com.fusiontech.bank.model.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (com.fusiontech.bank.model.TransactionType.class);
    }

    public double getAmount() {
        return _Amount;
    }

    public void setAmount(double value) {
        _Amount = value;
        has_Amount = true;
    }

    public java.lang.String getType() {
        return _Type;
    }

    public void setType(java.lang.String value) {
        _Type = value;
    }

    public double getCurrentBalance() {
        return _CurrentBalance;
    }

    public void setCurrentBalance(double value) {
        _CurrentBalance = value;
        has_CurrentBalance = true;
    }

    public java.util.Calendar getDateCreated() {
        return _DateCreated;
    }

    public void setDateCreated(java.util.Calendar value) {
        _DateCreated = value;
    }

    public int getAccountId() {
        return _AccountId;
    }

    public void setAccountId(int value) {
        _AccountId = value;
        has_AccountId = true;
    }

    public int getCustomerId() {
        return _CustomerId;
    }

    public void setCustomerId(int value) {
        _CustomerId = value;
        has_CustomerId = true;
    }

    public int getTransactionId() {
        return _TransactionId;
    }

    public void setTransactionId(int value) {
        _TransactionId = value;
        has_TransactionId = true;
    }

    public int getClearFlag() {
        return _ClearFlag;
    }

    public void setClearFlag(int value) {
        _ClearFlag = value;
        has_ClearFlag = true;
    }

    public double getAvailableBalance() {
        return _AvailableBalance;
    }

    public void setAvailableBalance(double value) {
        _AvailableBalance = value;
        has_AvailableBalance = true;
    }

    public com.fusiontech.bank.model.impl.runtime.UnmarshallingEventHandler createUnmarshaller(com.fusiontech.bank.model.impl.runtime.UnmarshallingContext context) {
        return new com.fusiontech.bank.model.impl.TransactionTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(com.fusiontech.bank.model.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (has_TransactionId) {
            context.startElement("http://www.fusiontech.com/bankservice/model/xsd/1.0", "transactionId");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(javax.xml.bind.DatatypeConverter.printInt(((int) _TransactionId)), "TransactionId");
            } catch (java.lang.Exception e) {
                com.fusiontech.bank.model.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (has_AccountId) {
            context.startElement("http://www.fusiontech.com/bankservice/model/xsd/1.0", "accountId");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(javax.xml.bind.DatatypeConverter.printInt(((int) _AccountId)), "AccountId");
            } catch (java.lang.Exception e) {
                com.fusiontech.bank.model.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (has_CustomerId) {
            context.startElement("http://www.fusiontech.com/bankservice/model/xsd/1.0", "customerId");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(javax.xml.bind.DatatypeConverter.printInt(((int) _CustomerId)), "CustomerId");
            } catch (java.lang.Exception e) {
                com.fusiontech.bank.model.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_DateCreated!= null) {
            context.startElement("http://www.fusiontech.com/bankservice/model/xsd/1.0", "dateCreated");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(javax.xml.bind.DatatypeConverter.printDate(((java.util.Calendar) _DateCreated)), "DateCreated");
            } catch (java.lang.Exception e) {
                com.fusiontech.bank.model.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_Type!= null) {
            context.startElement("http://www.fusiontech.com/bankservice/model/xsd/1.0", "type");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _Type), "Type");
            } catch (java.lang.Exception e) {
                com.fusiontech.bank.model.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (has_Amount) {
            context.startElement("http://www.fusiontech.com/bankservice/model/xsd/1.0", "amount");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(javax.xml.bind.DatatypeConverter.printDouble(((double) _Amount)), "Amount");
            } catch (java.lang.Exception e) {
                com.fusiontech.bank.model.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (has_AvailableBalance) {
            context.startElement("http://www.fusiontech.com/bankservice/model/xsd/1.0", "availableBalance");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(javax.xml.bind.DatatypeConverter.printDouble(((double) _AvailableBalance)), "AvailableBalance");
            } catch (java.lang.Exception e) {
                com.fusiontech.bank.model.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (has_CurrentBalance) {
            context.startElement("http://www.fusiontech.com/bankservice/model/xsd/1.0", "currentBalance");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(javax.xml.bind.DatatypeConverter.printDouble(((double) _CurrentBalance)), "CurrentBalance");
            } catch (java.lang.Exception e) {
                com.fusiontech.bank.model.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (has_ClearFlag) {
            context.startElement("http://www.fusiontech.com/bankservice/model/xsd/1.0", "clearFlag");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(javax.xml.bind.DatatypeConverter.printInt(((int) _ClearFlag)), "ClearFlag");
            } catch (java.lang.Exception e) {
                com.fusiontech.bank.model.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
    }

    public void serializeAttributes(com.fusiontech.bank.model.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeURIs(com.fusiontech.bank.model.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (com.fusiontech.bank.model.TransactionType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000pp"
+"sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000"
+"xq\u0000~\u0000\u0001ppsr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
+"\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun."
+"msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttribut"
+"esL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001"
+"Z\u0000\u0005valuexp\u0000p\u0000sq\u0000~\u0000\u0000ppsr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001"
+"\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004n"
+"amet\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0003ppsr\u0000 com.sun.msv.d"
+"atatype.xsd.IntType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000+com.sun.msv.datatype.xsd.I"
+"ntegerDerivedType\u0099\u00f1]\u0090&6k\u00be\u0002\u0000\u0001L\u0000\nbaseFacetst\u0000)Lcom/sun/msv/dat"
+"atype/xsd/XSDatatypeImpl;xr\u0000*com.sun.msv.datatype.xsd.Builti"
+"nAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.ConcreteT"
+"ype\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/lang/String;L\u0000\btypeNameq\u0000~\u0000 "
+"L\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpaceProcesso"
+"r;xpt\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0003intsr\u00005com.sun.msv"
+".datatype.xsd.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com"
+".sun.msv.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u0000*co"
+"m.sun.msv.datatype.xsd.MaxInclusiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000#com.s"
+"un.msv.datatype.xsd.RangeFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\nlimitValuet\u0000\u0012Lja"
+"va/lang/Object;xr\u00009com.sun.msv.datatype.xsd.DataTypeWithValu"
+"eConstraintFacet\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd.Data"
+"TypeWithFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFacetFixedZ\u0000\u0012needValueCheckFlag"
+"L\u0000\bbaseTypeq\u0000~\u0000\u001cL\u0000\fconcreteTypet\u0000\'Lcom/sun/msv/datatype/xsd/"
+"ConcreteType;L\u0000\tfacetNameq\u0000~\u0000 xq\u0000~\u0000\u001fppq\u0000~\u0000\'\u0000\u0001sr\u0000*com.sun.msv"
+".datatype.xsd.MinInclusiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000)ppq\u0000~\u0000\'\u0000\u0000sr\u0000"
+"!com.sun.msv.datatype.xsd.LongType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001bq\u0000~\u0000#t\u0000\u0004l"
+"ongq\u0000~\u0000\'sq\u0000~\u0000(ppq\u0000~\u0000\'\u0000\u0001sq\u0000~\u0000/ppq\u0000~\u0000\'\u0000\u0000sr\u0000$com.sun.msv.dataty"
+"pe.xsd.IntegerType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001bq\u0000~\u0000#t\u0000\u0007integerq\u0000~\u0000\'sr\u0000,c"
+"om.sun.msv.datatype.xsd.FractionDigitsFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\u0005sca"
+"lexr\u0000;com.sun.msv.datatype.xsd.DataTypeWithLexicalConstraint"
+"FacetT\u0090\u001c>\u001azb\u00ea\u0002\u0000\u0000xq\u0000~\u0000,ppq\u0000~\u0000\'\u0001\u0000sr\u0000#com.sun.msv.datatype.xsd."
+"NumberType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001dq\u0000~\u0000#t\u0000\u0007decimalq\u0000~\u0000\'q\u0000~\u0000=t\u0000\u000efract"
+"ionDigits\u0000\u0000\u0000\u0000q\u0000~\u00007t\u0000\fminInclusivesr\u0000\u000ejava.lang.Long;\u008b\u00e4\u0090\u00cc\u008f#\u00df\u0002"
+"\u0000\u0001J\u0000\u0005valuexr\u0000\u0010java.lang.Number\u0086\u00ac\u0095\u001d\u000b\u0094\u00e0\u008b\u0002\u0000\u0000xp\u0080\u0000\u0000\u0000\u0000\u0000\u0000\u0000q\u0000~\u00007t\u0000\fm"
+"axInclusivesq\u0000~\u0000A\u007f\u00ff\u00ff\u00ff\u00ff\u00ff\u00ff\u00ffq\u0000~\u00002q\u0000~\u0000@sr\u0000\u0011java.lang.Integer\u0012\u00e2\u00a0\u00a4"
+"\u00f7\u0081\u00878\u0002\u0000\u0001I\u0000\u0005valuexq\u0000~\u0000B\u0080\u0000\u0000\u0000q\u0000~\u00002q\u0000~\u0000Dsq\u0000~\u0000F\u007f\u00ff\u00ff\u00ffsr\u00000com.sun.msv"
+".grammar.Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003ppsr\u0000\u001b"
+"com.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000 L\u0000\fna"
+"mespaceURIq\u0000~\u0000 xpq\u0000~\u0000$q\u0000~\u0000#sq\u0000~\u0000\rppsr\u0000 com.sun.msv.grammar.A"
+"ttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\u0010xq\u0000~\u0000\u0003q\u0000~\u0000"
+"\u0014psq\u0000~\u0000\u0016ppsr\u0000\"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000x"
+"q\u0000~\u0000\u001dq\u0000~\u0000#t\u0000\u0005QNameq\u0000~\u0000\'q\u0000~\u0000Jsq\u0000~\u0000Kq\u0000~\u0000Sq\u0000~\u0000#sr\u0000#com.sun.msv."
+"grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000 L\u0000\fnamesp"
+"aceURIq\u0000~\u0000 xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004"
+"typet\u0000)http://www.w3.org/2001/XMLSchema-instancesr\u00000com.sun."
+"msv.grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000"
+"~\u0000\u0013\u0001q\u0000~\u0000[sq\u0000~\u0000Ut\u0000\rtransactionIdt\u00003http://www.fusiontech.com/"
+"bankservice/model/xsd/1.0q\u0000~\u0000[sq\u0000~\u0000\rppsq\u0000~\u0000\u000fq\u0000~\u0000\u0014p\u0000sq\u0000~\u0000\u0000ppq"
+"\u0000~\u0000\u0019sq\u0000~\u0000\rppsq\u0000~\u0000Nq\u0000~\u0000\u0014pq\u0000~\u0000Pq\u0000~\u0000Wq\u0000~\u0000[sq\u0000~\u0000Ut\u0000\taccountIdq\u0000~"
+"\u0000_q\u0000~\u0000[sq\u0000~\u0000\rppsq\u0000~\u0000\u000fq\u0000~\u0000\u0014p\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u0019sq\u0000~\u0000\rppsq\u0000~\u0000Nq\u0000~\u0000\u0014"
+"pq\u0000~\u0000Pq\u0000~\u0000Wq\u0000~\u0000[sq\u0000~\u0000Ut\u0000\ncustomerIdq\u0000~\u0000_q\u0000~\u0000[sq\u0000~\u0000\rppsq\u0000~\u0000\u000fq"
+"\u0000~\u0000\u0014p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0016ppsr\u0000!com.sun.msv.datatype.xsd.DateType\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000)com.sun.msv.datatype.xsd.DateTimeBaseType\u0014W\u001a@3"
+"\u00a5\u00b4\u00e5\u0002\u0000\u0000xq\u0000~\u0000\u001dq\u0000~\u0000#t\u0000\u0004dateq\u0000~\u0000\'q\u0000~\u0000Jsq\u0000~\u0000Kq\u0000~\u0000uq\u0000~\u0000#sq\u0000~\u0000\rppsq"
+"\u0000~\u0000Nq\u0000~\u0000\u0014pq\u0000~\u0000Pq\u0000~\u0000Wq\u0000~\u0000[sq\u0000~\u0000Ut\u0000\u000bdateCreatedq\u0000~\u0000_q\u0000~\u0000[sq\u0000~\u0000"
+"\rppsq\u0000~\u0000\u000fq\u0000~\u0000\u0014p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0016ppsr\u0000#com.sun.msv.datatype.xsd"
+".StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxq\u0000~\u0000\u001dq\u0000~\u0000#t\u0000\u0006stringsr"
+"\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000&\u0001q\u0000~\u0000Jsq\u0000~\u0000Kq\u0000~\u0000\u0081q\u0000~\u0000#sq\u0000~\u0000\rppsq\u0000~\u0000Nq\u0000~\u0000\u0014pq\u0000~\u0000Pq"
+"\u0000~\u0000Wq\u0000~\u0000[sq\u0000~\u0000Ut\u0000\u0004typeq\u0000~\u0000_q\u0000~\u0000[sq\u0000~\u0000\rppsq\u0000~\u0000\u000fq\u0000~\u0000\u0014p\u0000sq\u0000~\u0000\u0000p"
+"psq\u0000~\u0000\u0016ppsr\u0000#com.sun.msv.datatype.xsd.DoubleType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000x"
+"r\u0000+com.sun.msv.datatype.xsd.FloatingNumberType\u00fc\u00e3\u00b6\u0087\u008c\u00a8|\u00e0\u0002\u0000\u0000xq\u0000"
+"~\u0000\u001dq\u0000~\u0000#t\u0000\u0006doubleq\u0000~\u0000\'q\u0000~\u0000Jsq\u0000~\u0000Kq\u0000~\u0000\u0090q\u0000~\u0000#sq\u0000~\u0000\rppsq\u0000~\u0000Nq\u0000~"
+"\u0000\u0014pq\u0000~\u0000Pq\u0000~\u0000Wq\u0000~\u0000[sq\u0000~\u0000Ut\u0000\u0006amountq\u0000~\u0000_q\u0000~\u0000[sq\u0000~\u0000\rppsq\u0000~\u0000\u000fq\u0000~"
+"\u0000\u0014p\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u008csq\u0000~\u0000\rppsq\u0000~\u0000Nq\u0000~\u0000\u0014pq\u0000~\u0000Pq\u0000~\u0000Wq\u0000~\u0000[sq\u0000~\u0000Ut\u0000"
+"\u0010availableBalanceq\u0000~\u0000_q\u0000~\u0000[sq\u0000~\u0000\rppsq\u0000~\u0000\u000fq\u0000~\u0000\u0014p\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000"
+"\u008csq\u0000~\u0000\rppsq\u0000~\u0000Nq\u0000~\u0000\u0014pq\u0000~\u0000Pq\u0000~\u0000Wq\u0000~\u0000[sq\u0000~\u0000Ut\u0000\u000ecurrentBalanceq"
+"\u0000~\u0000_q\u0000~\u0000[sq\u0000~\u0000\rppsq\u0000~\u0000\u000fq\u0000~\u0000\u0014p\u0000sq\u0000~\u0000\u0000ppq\u0000~\u0000\u0019sq\u0000~\u0000\rppsq\u0000~\u0000Nq\u0000~"
+"\u0000\u0014pq\u0000~\u0000Pq\u0000~\u0000Wq\u0000~\u0000[sq\u0000~\u0000Ut\u0000\tclearFlagq\u0000~\u0000_q\u0000~\u0000[sr\u0000\"com.sun.ms"
+"v.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/ms"
+"v/grammar/ExpressionPool$ClosedHash;xpsr\u0000-com.sun.msv.gramma"
+"r.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersi"
+"onL\u0000\u0006parentt\u0000$Lcom/sun/msv/grammar/ExpressionPool;xp\u0000\u0000\u0000#\u0001pq\u0000"
+"~\u0000\u008bq\u0000~\u0000\u0098q\u0000~\u0000\u009fq\u0000~\u0000\nq\u0000~\u0000\u000eq\u0000~\u0000`q\u0000~\u0000gq\u0000~\u0000\u0089q\u0000~\u0000\u0096q\u0000~\u0000\u009dq\u0000~\u0000\u00a4q\u0000~\u0000\fq\u0000"
+"~\u0000pq\u0000~\u0000\u000bq\u0000~\u0000Mq\u0000~\u0000cq\u0000~\u0000jq\u0000~\u0000wq\u0000~\u0000\u0085q\u0000~\u0000\u0092q\u0000~\u0000{q\u0000~\u0000\u0099q\u0000~\u0000\u00a0q\u0000~\u0000\u00a7q\u0000"
+"~\u0000\u0006q\u0000~\u0000\u0007q\u0000~\u0000\u0015q\u0000~\u0000bq\u0000~\u0000iq\u0000~\u0000nq\u0000~\u0000\u00a6q\u0000~\u0000}q\u0000~\u0000\bq\u0000~\u0000\tq\u0000~\u0000\u0005x"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends com.fusiontech.bank.model.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(com.fusiontech.bank.model.impl.runtime.UnmarshallingContext context) {
            super(context, "----------------------------");
        }

        protected Unmarshaller(com.fusiontech.bank.model.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return com.fusiontech.bank.model.impl.TransactionTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  21 :
                        if (("currentBalance" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 22;
                            return ;
                        }
                        state = 24;
                        continue outer;
                    case  24 :
                        if (("clearFlag" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 25;
                            return ;
                        }
                        state = 27;
                        continue outer;
                    case  15 :
                        if (("amount" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 16;
                            return ;
                        }
                        state = 18;
                        continue outer;
                    case  6 :
                        if (("customerId" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 7;
                            return ;
                        }
                        state = 9;
                        continue outer;
                    case  9 :
                        if (("dateCreated" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 10;
                            return ;
                        }
                        state = 12;
                        continue outer;
                    case  27 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  12 :
                        if (("type" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 13;
                            return ;
                        }
                        state = 15;
                        continue outer;
                    case  0 :
                        if (("transactionId" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 1;
                            return ;
                        }
                        state = 3;
                        continue outer;
                    case  18 :
                        if (("availableBalance" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 19;
                            return ;
                        }
                        state = 21;
                        continue outer;
                    case  3 :
                        if (("accountId" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 4;
                            return ;
                        }
                        state = 6;
                        continue outer;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  21 :
                        state = 24;
                        continue outer;
                    case  8 :
                        if (("customerId" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.popAttributes();
                            state = 9;
                            return ;
                        }
                        break;
                    case  2 :
                        if (("transactionId" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  24 :
                        state = 27;
                        continue outer;
                    case  17 :
                        if (("amount" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.popAttributes();
                            state = 18;
                            return ;
                        }
                        break;
                    case  11 :
                        if (("dateCreated" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.popAttributes();
                            state = 12;
                            return ;
                        }
                        break;
                    case  20 :
                        if (("availableBalance" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.popAttributes();
                            state = 21;
                            return ;
                        }
                        break;
                    case  15 :
                        state = 18;
                        continue outer;
                    case  6 :
                        state = 9;
                        continue outer;
                    case  9 :
                        state = 12;
                        continue outer;
                    case  14 :
                        if (("type" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.popAttributes();
                            state = 15;
                            return ;
                        }
                        break;
                    case  27 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  12 :
                        state = 15;
                        continue outer;
                    case  23 :
                        if (("currentBalance" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.popAttributes();
                            state = 24;
                            return ;
                        }
                        break;
                    case  0 :
                        state = 3;
                        continue outer;
                    case  18 :
                        state = 21;
                        continue outer;
                    case  5 :
                        if (("accountId" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.popAttributes();
                            state = 6;
                            return ;
                        }
                        break;
                    case  26 :
                        if (("clearFlag" == ___local)&&("http://www.fusiontech.com/bankservice/model/xsd/1.0" == ___uri)) {
                            context.popAttributes();
                            state = 27;
                            return ;
                        }
                        break;
                    case  3 :
                        state = 6;
                        continue outer;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  21 :
                        state = 24;
                        continue outer;
                    case  24 :
                        state = 27;
                        continue outer;
                    case  15 :
                        state = 18;
                        continue outer;
                    case  6 :
                        state = 9;
                        continue outer;
                    case  9 :
                        state = 12;
                        continue outer;
                    case  27 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  12 :
                        state = 15;
                        continue outer;
                    case  0 :
                        state = 3;
                        continue outer;
                    case  18 :
                        state = 21;
                        continue outer;
                    case  3 :
                        state = 6;
                        continue outer;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  21 :
                        state = 24;
                        continue outer;
                    case  24 :
                        state = 27;
                        continue outer;
                    case  15 :
                        state = 18;
                        continue outer;
                    case  6 :
                        state = 9;
                        continue outer;
                    case  9 :
                        state = 12;
                        continue outer;
                    case  27 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  12 :
                        state = 15;
                        continue outer;
                    case  0 :
                        state = 3;
                        continue outer;
                    case  18 :
                        state = 21;
                        continue outer;
                    case  3 :
                        state = 6;
                        continue outer;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  19 :
                            state = 20;
                            eatText1(value);
                            return ;
                        case  25 :
                            state = 26;
                            eatText2(value);
                            return ;
                        case  7 :
                            state = 8;
                            eatText3(value);
                            return ;
                        case  21 :
                            state = 24;
                            continue outer;
                        case  16 :
                            state = 17;
                            eatText4(value);
                            return ;
                        case  4 :
                            state = 5;
                            eatText5(value);
                            return ;
                        case  10 :
                            state = 11;
                            eatText6(value);
                            return ;
                        case  13 :
                            state = 14;
                            eatText7(value);
                            return ;
                        case  24 :
                            state = 27;
                            continue outer;
                        case  15 :
                            state = 18;
                            continue outer;
                        case  22 :
                            state = 23;
                            eatText8(value);
                            return ;
                        case  6 :
                            state = 9;
                            continue outer;
                        case  9 :
                            state = 12;
                            continue outer;
                        case  27 :
                            revertToParentFromText(value);
                            return ;
                        case  12 :
                            state = 15;
                            continue outer;
                        case  1 :
                            state = 2;
                            eatText9(value);
                            return ;
                        case  0 :
                            state = 3;
                            continue outer;
                        case  18 :
                            state = 21;
                            continue outer;
                        case  3 :
                            state = 6;
                            continue outer;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _AvailableBalance = javax.xml.bind.DatatypeConverter.parseDouble(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_AvailableBalance = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _ClearFlag = javax.xml.bind.DatatypeConverter.parseInt(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_ClearFlag = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText3(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _CustomerId = javax.xml.bind.DatatypeConverter.parseInt(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_CustomerId = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText4(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Amount = javax.xml.bind.DatatypeConverter.parseDouble(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_Amount = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText5(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _AccountId = javax.xml.bind.DatatypeConverter.parseInt(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_AccountId = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText6(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _DateCreated = javax.xml.bind.DatatypeConverter.parseDate(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText7(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Type = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText8(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _CurrentBalance = javax.xml.bind.DatatypeConverter.parseDouble(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_CurrentBalance = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText9(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _TransactionId = javax.xml.bind.DatatypeConverter.parseInt(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_TransactionId = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

    }

}
